import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          hi, i&apos;m <a href="https://nextjs.org">sino</a>
        </h1>

        <p className={styles.description}>i&apos;m a software engineer 🚀</p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2 className="font-semibold">
              Junior Software Developer @ Teamgeek
            </h2>
            <p className="text-sm mb-5 text-gray-500">Jan 2021 - Dec 2021</p>
            <p>
              Developed and maintained frontend mobile responsive web
              applications built in React. In addition to React, styled
              components were used for styling and also made use of apollo to
              interact with a GraphQL API.
            </p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2 className="font-semibold">Graduate Software Engineer @ DVT</h2>
            <p className="text-sm mb-5 text-gray-500">Feb 2022 - Present</p>
            <p>
              A twelve-month graduate programme that provides extensive
              coaching. In addition to skills in software engineering
              technology, the programme includes soft skills coaching, training
              and experience in Agile, which is done in collaboration with the
              DVT Academy.
            </p>
          </a>

          {/* <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <p className="text-gray-500">created by sino</p>
      </footer>
    </div>
  );
}
